### ISSUE TITLE
Set up CI linting

### ISSUE THREAD

**Issue by grugnog** [getredash/contrib-helm-chart#1]
We need some basic linting - we can probably reproduce much of what the helm/charts repo does pretty easily

**Comment by grugnog** [comment]
@arikfr I have been roughing out some CI linting/testing on my fork (using free CircleCI plan) - https://github.com/grugnog/contrib-helm-chart/blob/master/.circleci/config.yml.
I was hoping Redash might be able to enable CircleCI for this repo?

**Comment by arikfr** [comment]
@grugnog CircleCI is enabled for the whole organization, so I think you need to create the `.circleci/config.yml` file and it will start working.

I also invited you to the Maintainers team, so you're part of the organization in case it's a permission thing on CircleCI.

**Comment by arikfr** [comment]
Btw, did you consider using GitHub Actions for this?

**Comment by grugnog** [comment]
@arikfr thanks for the help! I added a `.circleci/config.yml` but CircleCI is still saying a repo admin needs to add the project:
![image](https://user-images.githubusercontent.com/905689/70565286-9b933d00-1b46-11ea-9c2a-fbb37bd6c58a.png)

I did consider GitHub Actions, but mostly stuck with CircleCI as I noticed it was in use by Redash already and also used by various other Helm repos which makes for a helpful resource for getting minikube etc up and running.

**Comment by arikfr** [comment]
> I added a `.circleci/config.yml` but CircleCI is still saying a repo admin needs to add the project at https://circleci.com/add-projects/gh/getredash:

Done. :+1: https://circleci.com/workflow-run/61b6fa08-af86-44ef-928c-0049cb5522e7

**Comment by grugnog** [comment]
Thank you so much! It even passes :)

**Comment by arikfr** [comment]
Thank you! I just clicked a button 😅
