### ISSUE TITLE
Support external Redis

### ISSUE THREAD

**Issue by linux0x5c** [getredash/contrib-helm-chart#10]
I won't install dep with redis,how could use extra redis?

**Comment by grugnog** [comment]
@linux0x5c not currently, but it should be straightforward to add (same pattern as external Postgres)

**Comment by linux0x5c** [comment]
@grugnog Thanks all the same,I will try it

**Comment by thuandt** [comment]
@linux0x5c @grugnog I created PR #11 
It's including external redis server support and few enhancement update for 8.x version. I already tested internal on my company.

If you feel OK, please help me review my PR.
Thanks

**Comment by linux0x5c** [comment]
Hi, @thuandt ,thanks for your pr,I will try it.
