### ISSUE TITLE
Unable to connect AWS Elasticache Redis with redis_auth key

### ISSUE THREAD

**Issue by johnson-prabu** [getredash/contrib-helm-chart#104]
Hi Team, 

I am unable from redash to external_redis (AWS Elasticache Redis with redis_auth key). Kindly suggest the possibilities

**Comment by grugnog** [comment]
@johnson-prabu we use an external Redis, so I believe it is working - are you able to connect from a generic Redis client pod? If so, could you share your configuration (with sanitized secret values) and what the error logs are?

**Comment by johnson-prabu** [comment]
Once I have disabled the REDIS_AUTH, it is working fine. Now i am able to connect with Redis without Auth. Thanks for the response.

**Comment by johnson-prabu** [comment]
Also, As i went through the issue,  with Redis URL if we enable "--tls" then we may connect. Plsl let me know if it is already enabled.

**Comment by grugnog** [comment]
@johnson-prabu I am not sure - you might need to dig through the Redash code to figure that out - the only input the chart can provide is the `REDASH_REDIS_URL` environment variable.
