### ISSUE TITLE
Possibility of moving sensitive data to k8s secrets

### ISSUE THREAD

**Issue by johnson-prabu** [getredash/contrib-helm-chart#107]
Kindly move sensitive data like REDASH_DATABASE_PASSWORD, REDASH_REDIS_PASSWORD, REDASH_GOOGLE_CLIENT_SECRET to k8s secrets?

Here I can see only a few values.
https://github.com/getredash/contrib-helm-chart/blob/master/templates/secrets.yaml

**Comment by grugnog** [comment]
These are already stored in secrets - the first 2 are in secrets managed by dependent charts:
https://github.com/getredash/contrib-helm-chart/blob/master/templates/_helpers.tpl#L104
https://github.com/getredash/contrib-helm-chart/blob/master/templates/_helpers.tpl#L126
https://github.com/getredash/contrib-helm-chart/blob/master/templates/_helpers.tpl#L231

**Comment by johnson-prabu** [comment]
Still it is not on secrets, when we are providing "REDASH_DATABASE_PASSWORD, REDASH_REDIS_PASSWORD, REDASH_GOOGLE_CLIENT_SECRET" through values.yml

env:
  REDASH_DATABASE_USER:
  REDASH_DATABASE_PASSWORD:
  REDASH_DATABASE_HOSTNAME:
  REDASH_DATABASE_PORT:
  REDASH_DATABASE_DB:
  REDASH_REDIS_PASSWORD:
  REDASH_REDIS_HOSTNAME:
  REDASH_REDIS_PORT:
  REDASH_REDIS_DB:

**Comment by CarKsby** [comment]
Hey

I've recently been asked to create a Redash instance in a cluster that is managed by argo, and managed to make some tweaks such that the values.yaml doesn't show values and doesn't generate it's own secrets, instead using sealed secrets for all those values (since argo uses kustomize) if you'd like me to write that up either here or as a section on the README?

**Comment by grugnog** [comment]
@johnson-prabu You shouldn't be passing secrets via `env:` - there are configuration options available (externalPostgreSQLSecret, externalRedisSecret) that give you the ability to reference a k8s secret if you don't want to use the dependent charts (which create secrets automatically). As @CarKsby mentioned these secrets can be deployed by sealed secrets, cloud provider integration secrets or whatever other mechanism you use for managing secrets.
