### ISSUE TITLE
Monitoring redash

### ISSUE THREAD

**Issue by vivekhimalayas** [getredash/contrib-helm-chart#110]
I have installed redash using helm chart. How do we monitor this redash? Can we throw metrics from redash to prometheus?

**Comment by z0rc** [comment]
Redash doesn't expose metrics in Prometheus format. You can archive metrics scraping via https://redash.io/help/open-source/admin-guide/maintenance#Monitoring and https://github.com/buildsville/redash-exporter. Though is this setup requires exposing super admin API key and running custom exporter, therefore it's out of scope for helm chart.

**Comment by grugnog** [comment]
Thanks @z0rc!
