### ISSUE TITLE
Set Backward Compatibility check for ingress api 

### ISSUE THREAD

**Issue by armandleopold** [getredash/contrib-helm-chart#111]
Hello, i am on a kubernetes cluster version v1.15.5 which only has ingress api version : `apiVersion: extensions/v1beta1`

When upgrading with the latest helm chart version :  `3.0.0-beta`

I get :

```yaml
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

Which i assume comes from  :

https://github.com/getredash/contrib-helm-chart/blob/02bb00f01821c22844d05abe7e74a93c088b7967/templates/ingress.yaml#L5

Can you add compatibility checks for ingress api please ? 

Take exemple from Bitnami airflow web ingress where it has : 

https://github.com/bitnami/charts/blob/d81a6141c356c251d383c598cd2c01d5c87d4a1f/bitnami/airflow/templates/web/ingress.yaml#L2

that comes from a template file :

https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl

Thanks !

**Comment by z0rc** [comment]
It's arguable that supporting outdated Kubernetes API versions is worth of chart maintainers time. You can always use previous chart releases. You Kubernetes version is EOL for year and a half. It's better to plan upgrading your cluster, rather that dragging public charts into support of outdated version.

**Comment by armandleopold** [comment]
Even if i create a pull request ?

**Comment by z0rc** [comment]
@armandleopold How many users, except yourself, are going to need this? Even if you submit a PR, maintainers won't be able to test it and the new code would remain in their responsibility.
Your options are:
- use older version of chart
- fork and maintain your own changes
- update your kubernetes cluster

**Comment by grugnog** [comment]
Agreed - you are welcome to maintain a fork, but it's hard enough to keep up with the set of currently maintained k8s versions without adding conditional logic for insecure outdated versions.

**Comment by armandleopold** [comment]
Ok, we are going to update our kubernetes cluster anyway, just postponed using the latest helm.
thx guys.
