### ISSUE TITLE
Add possibility to add extra libs (ex : LDAP) to redash frontend

### ISSUE THREAD

**Issue by armandleopold** [getredash/contrib-helm-chart#114]
Hello, 

We use redash in a enterprise context, we have created a custom docker image just tin install LDAP : 

```Dockerfile
FROM redash/redash:10.1.0.b50633
USER root
RUN pip install --no-cache-dir ldap3
USER redash
```

Can we implement a logic  of bootstrap script that evaluate a configmap or a variable and install the requested python libraries before starting ?

I would be much simpler for everyone using the LDAP fonctionnality to have that capability.

**Comment by grugnog** [comment]
@armandleopold I don't think we would want to install libraries on bootstrap - that seems risky from a security and reliability perspective. Using a docker image does add a step but means that organizations get immutable deployments and rollback etc.

**Comment by armandleopold** [comment]
I agree with you for the security reason, but for the immutable deployment and rollback, we go through a docker repository proxy that keeps every containers going into the company. 
The implementation of this capability (above) would be interesting as it would enable us to delegate maintenance of external ressources to community.
