### ISSUE TITLE
Helm Repo Not up to Date

### ISSUE THREAD

**Issue by grifonas** [getredash/contrib-helm-chart#116]
Hello,

It appears that the helm repo `https://getredash.github.io/contrib-helm-chart/` is not up to date. 

Steps to reproduce: 
```
helm repo add redash https://getredash.github.io/contrib-helm-chart/
helm repo update
helm search repo redash
```
**Result**:
```NAME         	CHART VERSION	APP VERSION 	DESCRIPTION
redash/redash	2.4.0        	8.0.2.b37747	Redash is an open source tool built for teams t...
```

**Desired result**: 
The version specified in the Chart.yaml is `3.0.0-beta1` (appVersion: `10.0.0.b50363`).

**Comment by grugnog** [comment]
Thanks - not sure what happened there, but this is now updated:
`redash/redash	3.0.0        	10.0.0.b50633	Redash is an open source tool built for teams t...`
