### ISSUE TITLE
Service account name variable not used

### ISSUE THREAD

**Issue by mgobec** [getredash/contrib-helm-chart#123]
https://github.com/getredash/contrib-helm-chart/blob/82e54f575ad25ea4ec76d58c3f92cef4dc6e6214/templates/serviceaccount.yaml#L5

This should reference .Values.serviceAccount.name instead of redash.serviceAccountName

**Comment by grugnog** [comment]
This looks correct to me - it is referencing this helper template, which further references the correct variable: https://github.com/getredash/contrib-helm-chart/blob/master/templates/_helpers.tpl#L551
