### ISSUE TITLE
Redis failure connection lost when helm upgrade/install

### ISSUE THREAD

**Issue by armandleopold** [getredash/contrib-helm-chart#128]
When we upgrade/install redash,

The redis statefulset redeploy a new pod, creating an interruption and connection failure in redash frontend & workers,
Creating error 500 from frontend and workers not reconnecting.

**Workaround :** 

![image](https://user-images.githubusercontent.com/7100281/177991613-9bedc5b4-1ca7-485e-a984-a0af947f5ed3.png)

Can we manage that ?

**Comment by aberenshtein** [comment]
👍🏻
