### ISSUE TITLE
External Postgres : database not initialised automatically ( Login Error )

### ISSUE THREAD

**Issue by ani1203** [getredash/contrib-helm-chart#135]
**psycopg2.errors.UndefinedTable: relation "organizations" does not exist** 

Hi team, I am getting the below error while trying to connect to Redash setup on Kubernetes using helm, all the pods are working fine, but while trying to login getting the following error, I am using external Postgres setup on RDS:

```
[2022-09-08 15:02:25,520][PID:11][ERROR][redash.app] Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "organizations" does not exist
LINE 2: FROM organizations 
             ^
```

while searching for the error, got the following on the docker setup , it is recommended to use below command in case db is not initialised :

`docker-compose run --rm server create_db
`

Link for reference: https://discuss.redash.io/t/build-error-with-docker-compose/3811/3

Can you tell the equivalent for kuebrnetes ?

**Comment by ani1203** [comment]
Solution : 


`It was issue with the user permission , we have created another user for Redash which was giving error , but using the default DB (Postgres )and User (Postgres) will solve the issue.`

**Comment by jonathon2nd** [comment]
https://github.com/getredash/contrib-helm-chart/issues/113#issuecomment-1231381031

**Comment by AndrewChubatiuk** [comment]
now entrypoint scripts are running both db creation and db migration. so this should be fixed now
