### ISSUE TITLE
Problem Deploy Redash k8s

### ISSUE THREAD

**Issue by jversolatocreditas** [getredash/contrib-helm-chart#137]
Hello guys,

i've been tried deploy my Redash Chart:

redash     reda-69ff-redash-postgresql                   Secret          -    create  -       reconcile  -   -
reda-69ff-redash-postgresql                   Service         -    create  -       reconcile  -   -
reda-69ff-redash-postgresql-hl                Service         -    create  -       reconcile  -   -
reda-69ff-redash-redis                        Secret          -    create  -       reconcile  -   -
reda-69ff-redash-redis-configuration          ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-redis-headless               Service         -    create  -       reconcile  -   -
reda-69ff-redash-redis-health                 ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-redis-master                 Service         -    create  -       reconcile  -   -
reda-69ff-redash-redis-replicas               Service         -    create  -       reconcile  -   -
reda-69ff-redash-redis-scripts                ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-release                      ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-release                      Deployment      -    create  -       reconcile  -   -
reda-69ff-redash-release                      Secret          -    create  -       reconcile  -   -
reda-69ff-redash-release                      Service         -    create  -       reconcile  -   -
reda-69ff-redash-release-adhocworker          Deployment      -    create  -       reconcile  -   -
reda-69ff-redash-release-genericworker        Deployment      -    create  -       reconcile  -   -
reda-69ff-redash-release-install              Job             -    create  -       reconcile  -   -
reda-69ff-redash-release-postgresql           Secret          -    create  -       reconcile  -   -
reda-69ff-redash-release-postgresql           Service         -    create  -       reconcile  -   -
reda-69ff-redash-release-postgresql-headless  Service         -    create  -       reconcile  -   -
reda-69ff-redash-release-redis                ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-release-redis                Secret          -    create  -       reconcile  -   -
reda-69ff-redash-release-redis-headless       Service         -    create  -       reconcile  -   -
reda-69ff-redash-release-redis-health         ConfigMap       -    create  -       reconcile  -   -
reda-69ff-redash-release-redis-master         Service         -    create  -       reconcile  -   -
reda-69ff-redash-release-scheduledworker      Deployment      -    create  -       reconcile  -   -
reda-69ff-redash-release-scheduler            Deployment      -    create  -       reconcile  -   -
reda-69ff-redash-release-test-connection      Pod             -    create  -       reconcile  -   -
reda-69ff-redash-release-upgrade              Job             -    create  -       reconcile  -   -
redash-postgresql                             StatefulSet     -    create  -       reconcile  -   -
redash-redis                                  ServiceAccount  -    create  -       reconcile  -   -
redash-redis-master                           StatefulSet     -    create  -       reconcile  -   -
redash-redis-replicas                         StatefulSet     -    create  -       reconcile  -   -
redash-release                                ServiceAccount  -    create  -       reconcile  -   -
redash-release-postgresql                     StatefulSet     -    create  -       reconcile  -   -
redash-release-redis-master                   StatefulSet     -    create  -       reconcile  -   -

But when i saw in my console the message below:

10:07:42AM:  ^ Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "reda-69ff-redash-release-8664b74554" has timed out progressing.)

kapp: Error: waiting on reconcile deployment/reda-69ff-redash-release (apps/v1) namespace: redash:
  Finished unsuccessfully (Deployment is not progressing: ProgressDeadlineExceeded (message: ReplicaSet "reda-69ff-redash-release-8664b74554" has timed out progressing.))
2022/11/01 10:07:43 error to deploy application: deploy failed: exit status 1

Does anyone know what can it be?

**Comment by grugnog** [comment]
There isn't enough detail here to identify an issue - would need to check the logs for the failing ReplicaSet pods
