### ISSUE TITLE
404 not found after deploying

### ISSUE THREAD

**Issue by kjell-van-straaten** [getredash/contrib-helm-chart#138]
Deployment of redash using this helm chart seems succesfull on our k8s server. Afterwards however I cannot seem to locate the endpoint (i.e., url) of the service. Eitherway I think this is a dumb question but I couldn't find where to access redash after deployment.

I tried CLUSTER_IP/NAME as usually works on k8s. I hope you can help me out how to configure the endpoint.

**Comment by grugnog** [comment]
The chart outputs instructions for connection (which depend on your configuration) on the command line after a deploy: https://github.com/getredash/contrib-helm-chart/blob/master/templates/NOTES.txt
