### ISSUE TITLE
https://getredash.github.io/contrib-helm-chart/ is down

### ISSUE THREAD

**Issue by domrod** [getredash/contrib-helm-chart#141]
Website https://getredash.github.io/contrib-helm-chart/ is down for more than a week.

Without it, it is impossible do deploy redash with a helm package.

Any idea when it could be online again ?

**Comment by dafrenchyman** [comment]
I just ran into the same problem so I tried rolling my own helm chart to deploy, but it looks like the `postgres` and `redis` versions that are being used as dependencies have been deprecated from Bitnami. I attempted to up them to newer versions, and it's like opening a whole can of worms (the newer Bitnami Postgres images changed the keys of where it stored it's secrets, etc...).

Eventually, I figured out a way to get it going off the old versions (use `repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami` for the dependencies.

If your stuff isn't mission critical, and you're not terrified of using my personal helm chart repo, go for it: `charts.mrsharky.com`. It took me a few attempts to get it to work so `redash` is at version `3.0.2`. You can inspect the contents of the repo through the index at [https://charts.mrsharky.com/index.yaml](https://charts.mrsharky.com/index.yaml), and you'll see a link to the `.tgz` file in there, if you want to inspect what's there.

Needless to say: Use at your own risk.

**Comment by domrod** [comment]
Thanks a lot. 

I managed to redeploy my redash cluster thanks to your repo charts.mrsharky.com.

Yes, it is not a business critical platform but still useful. 

Maybe I will have to do like you, to fork your repository in order to have something working in the future, as I see that Bitnami does not seem ready to maintain https://getredash.github.io/contrib-helm-chart/.

Thanks for the great job @dafrenchyman .

Cheers

**Comment by grugnog** [comment]
This is hosted by Github - it looks like you happened to try it during an sporadic outage: https://www.githubstatus.com/incidents/zf2tk6x40gmh

**Comment by dafrenchyman** [comment]
It's still down. It gives a 404 not found.

**Comment by dafrenchyman** [comment]
It's been down for a while
