### ISSUE TITLE
Chart accepts `redis.existingSecret`

### ISSUE THREAD

**Issue by chiemerieezechukwu** [getredash/contrib-helm-chart#142]
This helm chart supports `redis.existingSecret` as one of its values but this is not stated in the README

https://github.com/getredash/contrib-helm-chart/blob/e13e1fe6646ae51bfbe00d3eafd817e3c4af8380/templates/_helpers.tpl#L129-L130

**Comment by AndrewChubatiuk** [comment]
hey @chiemerieezechukwu 
.Values.redis.existingSecret is not in readme as it's a value from dependency chart https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
