### ISSUE TITLE
Broken Github Pages https://getredash.github.io/contrib-helm-chart/

### ISSUE THREAD

**Issue by pavelkrolov** [getredash/contrib-helm-chart#157]
Hello

https://getredash.github.io/contrib-helm-chart/ gives 404 error, makes harder to use Redash helm chart, could you please fix it :)

**Comment by justinclift** [comment]
Where are you getting getredash.io from?

**Comment by pavelkrolov** [comment]
From README.md

https://github.com/getredash/contrib-helm-chart/blob/master/README.md?plain=1#L27

**Comment by justinclift** [comment]
Interesting.  Didn't personally know that website url was even a thing. :wink:

And you're right, that clearly needs looking into as well. :smile:

**Comment by AndrewChubatiuk** [comment]
this website is for charts only and it works properly
https://getredash.github.io/contrib-helm-chart/index.yaml
to get information about arguments to pass please use [readme](https://github.com/getredash/contrib-helm-chart/blob/master/README.md)
