### ISSUE TITLE
Trouble exposing redash with Istio

### ISSUE THREAD

**Issue by bubilla** [getredash/contrib-helm-chart#19]
Hello, I am currently exhibiting a series of Services through Istio. However, when it comes to exposing redash I am having problems.
First I present the configuration to expose the service with istio:

`apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-name
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "subdomain.domain.com"
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
    hosts:
    - "subdomain.domain.com"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
  namespace: istio-system
spec:
  hosts:
  - "subdomain.domain.com"
  gateways:
  - gateway-name
  http:
  - match:
    - uri:
        exact: /redash
    - uri:
        prefix: /redash/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: redash.default.svc.cluster.local
        port:
          number: 80`

However, when I access the service through the URL https://subdomain.domain.com/redash, I receive this URL:

https://subdomain.domain.com/login?next=https%3A%2F%2Fsubdomain.domain.com%2F

Any idea why this can happen?

**Comment by grugnog** [comment]
@bubilla I haven't used Istio much, so not sure I can help, but perhaps the paths are not getting rewritten properly, and not getting  Redash is expecting to receive requests on /redash, so is generating URLs back to /?

**Comment by bubilla** [comment]
The rewrite "/" indicates that the subdomain.domain.com/redash url will be treated as root.
I have exposed other services and it works correctly.

I have made this change:

- match:
- uri:
Exact: /
- uri:
prefix: /
write again:
uri: "/"
route:
- destination:
host: redash.default.svc.cluster.local
Port:
number: 80

And now I can access.

I wish I could access with the subpath / redash
