### ISSUE TITLE
Add chart package repository and CI build

### ISSUE THREAD

**Issue by grugnog** [getredash/contrib-helm-chart#2]
Various options here - the simplest is to use Github Pages, but we could also publish to a Google Cloud Store or S3 repository

**Comment by arikfr** [comment]
What's the benefit of S3/GCS (or what's the downside from GH Pages)?

**Comment by grugnog** [comment]
I think S3/GCS has a simpler build process - I think the main benefit of GitHub Pages is that it doesn't depend on anyone paying the bill :)

**Comment by grugnog** [comment]
@arikfr for #13 to work I will need perms or a little help from a Github admin getting 2 SSH deploy keys configured in Github and CircleCI - 1 read-only (for the test job) and 1 read-write (for the Github Pages push).

**Comment by grugnog** [comment]
@arikfr I was able to add private keys to the CircleCI project.
The only thing remaining here is for someone to add corresponding deploy keys to this repo - would you be able to help with this? Alternatively I can do this if you can adjust my perms.

Read only key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC473df2iBrFfge18Xta67ZlCVQRIS47wCFKZ9VMLeIulfDE4t1CyAWVyi461zfUuyoQ1j0npetPI/DTE+JBc6Snt02Hn3Lt/Iec3gqYib+CdQzm88I7qBzlE3yw12kJvDUff3ez6B2sOtbULAcHyoqsos68G+r1dpU2YLMrMM4lVCxihA6JXyvfUpptJSAmyuHg8ioe72DIvVn+XRGuLZnOmL2EO4MaT3epWWFJkgezGg9MkFb0VxPBlnFfEy1AflFvvBSDoIeeASj74nXOVObpU1D983S9mxST8oP6K4Z5WTWcOderyTpKZsf3NhqvMLzEybCrlCcxoEJfFL/6Js/Lp8P189196FNZ+sMAtabL2W7AGrNGMqpTLQjrW4C3ZoxiIBSLgWV3nyvg6rNsijDVCHyY7kSQBdmqjbyaJ9DX1SKkEYD/f+x7XkdLcEULpKWxgzbf/RQXzaeyvJjulwJhWJD3nyUILc5S3SizhdGWqhMmtzXj/ZVAvLtfEfaT9U= redashro@localhost
```

Read-write key (check the "write access" box):
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4xBcjX3G77G/Jw1ZvUsS0eHMEcvUKGmRAYBSmpEfa7Tw0Meg2oRXqruO5paWR1YF9hF+7OgB9UPcuL+9fXK465KvGpy6iI+9cvLX7+NGt/lcbi1y4vfJc6MvDyI0jcS2REOqMkz93ilypvtd9QiNgGNQYIg0KN4RLpx6vIPPWXgyPKye0gmjiFbWmkKzMU53yPvFg8hzZ/BuJ3l2KZdwjMoYVRVna8XIAq8Rgv1z4+fidCU+K1su9ufuLH8l1ZKw1700TXJbNV4i0apabDSga+4LLmvp0vrdItBhCaTw5V9WYU+Q7+YFA3J+3uKQ/qIREp+6sdoU53//ykG8K/xxnl8a6mzXUvUVHWP7sOnM++bPlvR5tpKfFojPFertcTNxRS/1DIuIX9zZVJTru6BGwS7CFbYXTfDMVtucqGYCGLS+BltowoyhGdBxYQu70zHK5TtYxb7XDA3PkWnL1ANUydYE9McOJjotBiUnpdyYTKePvc71DFbPOtMzPcoFIPus= redashrw@localhost
```

**Comment by ekampf** [comment]
@arikfr ping :)

**Comment by arikfr** [comment]
@grugnog when I try adding either of the keys, I get a "Key already in use message". Any idea what this is about?

**Comment by grugnog** [comment]
@arikfr ahh - I think that must be because I added them on my fork to test :man_facepalming:. I just removed them - can you retry?

**Comment by grugnog** [comment]
@arikfr any progress?

**Comment by grugnog** [comment]
@arikfr Not having a locating to host the charts seems to be causing some confusion (see #2) - if you can add the keys that would be great, but if not I might just set up a chart repository on GCP.

**Comment by arikfr** [comment]
@grugnog done!

Sorry it took me so long. :-(

**Comment by grugnog** [comment]
@arikfr no problem for the delay, I am getting errors from Github that the read-write key is marked read-only though (https://circleci.com/gh/getredash/contrib-helm-chart/7). Would you be able to check the one labeled redashrw has the write access checkbox checked?

**Comment by arikfr** [comment]
I readded the keys again, just in case I mixed them up & triggered the job again. Hopefully it works this time 🤞

**Comment by arikfr** [comment]
It failed again. I then tried making both keys as read/write and it still failed. There is a third key which was added by CircleCI and it's read only. Maybe it's using this one and not the ones you created?

**Comment by arikfr** [comment]
I removed the third key and it's working now 👍

**Comment by grugnog** [comment]
@arikfr wonderful! Thanks so much for your help with this!!
