### ISSUE TITLE
Set configuration with command line

### ISSUE THREAD

**Issue by bubilla** [getredash/contrib-helm-chart#21]
Hi everyone.
I am trying to modify the configuration data related to sendgrid mail. I am currently running this command:

helm install --set mail.server = smtp.sendgrid.net --set mail.port = 587 --set mail.useTls = true \
--set mail.username = "value"  \
--set mail.password = "value" \
--set mail.defaultSender = "value" --set googleOAuth.enabled = true \
--set googleOAuth.redashGoogleClientId = "value"  \
--set googleOAuth.redashGoogleClientSecret = "value" my-release redash / redash

But when entering Settings -> Account I am getting the following message:

"It looks like your mail server isn't configured. Make sure to configure it for the invite emails to work."

My question is the following: Am I executing the command correctly or is it just a credential issue?

Also, how can I display this command if I am modifying the respective values?

Thanks

**Comment by bubilla** [comment]
i try this but i have the same problem:

helm install --set server.env.mail.server=smtp.sendgrid.net --set server.env.mail.port=587 --set server.env.mail.useTls=true \
--set server.env.mail.username=value \
--set server.env.mail.password=value \
--set server.env.mail.defaultSender=value --set server.env.googleOAuth.enabled=true \
--set server.env.googleOAuth.redashGoogleClientId=value \
--set server.env.googleOAuth.redashGoogleClientSecret=value redash redash/redash

**Comment by bubilla** [comment]
any idea?

**Comment by grugnog** [comment]
@bubilla guessing you figured this out, but the above configuration parameters didn't exist in v1 (not sure where they came from in fact!) - `env` accepted keys matching the documented variables at https://redash.io/help/open-source/admin-guide/env-vars-settings
For v2, which I just pushed a beta for there are now proper (and documented) chart variables for each environment variable - hopefully this should make things simpler all round.
