### ISSUE TITLE
Bug when sending invitation by mail

### ISSUE THREAD

**Issue by bubilla** [getredash/contrib-helm-chart#23]
Hello, I am currently exposing the service through istio and it works correctly.

I have sent an invitation email, but when I open the email link, it generates the following url:

http: ///invite/IjUi.ETWeOQ.DutSINrsKwE5yIC

losing the subdomain and the associated domain

But if I access the same url with the subdomain and domain as the following example it works correctly for me:

http://subdomain.domain.com/invite/IjUi.ETWeOQ.DutSINrsKwE5yIC

Any way to solve this error?

**Comment by grugnog** [comment]
@bubilla perhaps you need to set `REDASH_HOST` (`server.host` in the v2 beta)?

**Comment by bubilla** [comment]
Thanks, I added this in values.yaml

env:
  PYTHONUNBUFFERED: 0
  REDASH_LOG_LEVEL: "INFO"
  REDASH_HOST: subdomain.domain.com
