### ISSUE TITLE
Postgresql startup errors with new setup - data directory "/bitnami/postgresql/data" has group or world access

### ISSUE THREAD

**Issue by drobakowski** [getredash/contrib-helm-chart#46]
Hi there,

we are trying to run this chart on our kubernetes cluster and have some startup errors with Postgresql when persistence is enabled:
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/81381/92709638-6165fe80-f357-11ea-87cb-c141cbe1a3e6.png">

Looks like this could be a problem with the version of the Postgresql chart or image: https://github.com/bitnami/bitnami-docker-postgresql/issues/91. Maybe this also correlates to #41.

Any ideas on how to fix this?

**Comment by juanvasquezreyes** [comment]
If persistence is not that critical for you, you can disable it and it works

persistence:
    # postgresql.persistence.enabled -- Use a PVC to persist PostgreSQL data (when postgresql chart enabled)
    enabled: false

**Comment by jalberto** [comment]
persistence is critical for 90% DB usage, the solution is to bump the requirement to the latest chart version

**Comment by mansunkuo** [comment]
You can try to add `--set postgresql.volumePermissions.enabled=true` when you deploy your Helm chart. The related setting of Bitnami PostgreSQL Helm chart is [here](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/statefulset.yaml#L66).

**Comment by grugnog** [comment]
Closing this - setting perms isn't needed on most clusters, but as mentioned above can be enabled if needed.
