### ISSUE TITLE
Document step to download dependencies

### ISSUE THREAD

**Issue by posix4e** [getredash/contrib-helm-chart#6]
This repo seems premature and there's no way to use it. I tried using it locally even and i get 
```
$ helm install charts/redash/ --name redash --set cookieSecret=verysecret 
Error: found in requirements.yaml, but missing in charts/ directory: redis, postgresql

```

No way to add it remotely

**Comment by gabrielmv** [comment]
I got everything (minus email) up and running with this chart. I had the same problem with PostgreSQL.
 Are you using an external db and Redis?

My Redash, workers and Redis are running on GKE and my postgres is running on Google Cloud SQL.

For it to work I removed Postgres from the requirements

**Comment by posix4e** [comment]
Got it

**Comment by grugnog** [comment]
@posix4e I think you need to download the dependencies running `helm dependency update` in the redash directory. The README is missing this step (it wasn't required previously as the chart was in the same repository as the dependencies).

**Comment by grugnog** [comment]
Now we have packaging working (which bundles deps) I believe this can be closed
