### ISSUE TITLE
Ques: What values do I need?

### ISSUE THREAD

**Issue by joehoeller** [getredash/contrib-helm-chart#65]
What values do I need to fill in to:

1. externalPostgreSQL
2. externalPostgreSQLSecret
3. externalRedis
4. externalRedisSecret
5. postgresql.persistence.storageClass
6. redash.secretKey

Which exposes nodePort to reach redash on a URL?

A) service.port and service.type?
B)  ?

**Comment by joehoeller** [comment]
@jezdez can u plz supply how to open a nodePort?

**Comment by jezdez** [comment]
Sorry,  I have no idea, I haven't worked on this volunteer project, but @grugnog seems to be the person with the most commits, maybe they can help?

**Comment by joehoeller** [comment]
Thanks. Yeah I can’t seem to make the helm chart work.

**Comment by grugnog** [comment]
@joehoeller you shouldn't need any of the "external" values unless you are using an external Redis and Postgres - I would suggest starting with the basic setup described here and then adjusting once you have it working: https://github.com/getredash/contrib-helm-chart#installing-the-chart

**Comment by joehoeller** [comment]
I got it going w external Postgres ;)

**Comment by billchen8888** [comment]
I am trying to do the same, could you please paste your sample settings?  I spent days but still could not make it work yet.

Thanks.
