### ISSUE TITLE
Support setting `ingressClassName` via values

### ISSUE THREAD

**Issue by z0rc** [getredash/contrib-helm-chart#77]
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

Instead of using annotations, it's expected to set `ingressClassName` in ingress spec. Currently ingress template doesn't support this.

**Comment by rlees85** [comment]
https://github.com/getredash/contrib-helm-chart/issues/94

Related... if no-ones submitted a PR for this by tomorrow morning I'll try and do one.
