### ISSUE TITLE
Default redash helm deployment failing with postgres pod stuck in crash loop

### ISSUE THREAD

**Issue by wrhenverus** [getredash/contrib-helm-chart#78]
After some period of successful deployment, the Redash postgres server is failing and get’s stuck in a crashBackoffLoop with this log message:

FATAL:  data directory "/bitnami/postgresql/data" has group or world access
DETAIL:  Permissions should be u=rwx (0700).

From what I’ve read, it appears that when the postgres pod get is restarted, there is some change in the permissions which prevents the postgres pod from properly coming back online.

**Comment by grugnog** [comment]
@wrhenverus I think this is a factor of your cluster volume provisioning - #46 has a potential solution.
