### ISSUE TITLE
Latest Helm chart not released

### ISSUE THREAD

**Issue by armandleopold** [getredash/contrib-helm-chart#80]
Hello, 
You have your chart version which is : `2.3.1` latest with a bug fix.
But in the chart repo we only have `2.3.0`
Please update your chart repo.

Thx <3

**Comment by avnerv** [comment]
Any update on this?

**Comment by grugnog** [comment]
@armandleopold @avnerv So sorry about this - I hadn't noticed that the automated build didn't publish properly. It's published now!
